# Generated by Django 4.0.2 on 2022-02-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_category_name_alter_equipment_name_and_more'),
        ('main_app', '0008_alter_recipe_ingredient'),
    ]

    operations = [
    ]
