# Generated by Django 4.0.2 on 2022-02-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_comment'),
        ('main_app', '0011_remove_trip_destination'),
    ]

    operations = [
    ]
